project:
  type: website
  output-dir: docs
  preview:
    port: 4321

website:
  title: "Georgetown DSAN Mentorship Program"
  favicon: "favicon.png"
  sidebar:
    id: mainnav
    style: "floating"
    title: "Georgetown DSAN Mentorship Program"
    search: false
    contents:
      - text: "Back to Top"
        href: "#top-of-page"

format:
  html:
    theme: default
    css:
      - styles.css
    grid:
      sidebar-width: 150px
      body-width: 1200px
      margin-width: 380px
      gutter-width: 1.5rem



